version: '3.8'

services:
  web:
    build:
      context: ./docker/web
      args:
        DOCKER_USER: dockeruser
    #    user: "${UID}:${GID}"
    volumes:
      - ./application:/var/www
    ports:
      #- 5137:5137
      #- 8000:8000
      - 3000:3000
      - 3001:3001
      - 3002:3002
    #restart: always

  nginx:
    image: nginx
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./application:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/cert/localhost+1-key.pem:/etc/certs/localhost-key.pem
      - ./docker/cert/localhost+1.pem:/etc/certs/localhost.pem
    #restart: always
    depends_on:
      - web

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
#    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql:db
    depends_on:
      - mysql
      - nginx
      #- web
    volumes:
      - /sessions

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_UI_PORT:-8025}:8025'
